### ISSUE TITLE
Polish the documentation to require less knowledge about Docker to use this

### ISSUE THREAD

**Issue by timabbott** [galexrt/docker-zulip#118]
We should write a really polished HOWTO guide with every step required to get docker-zulip up and running, starting with links to how to install a current enough Docker on the Docker docs, a list of the configuration fields in `docker-compose.yml` that need to be manually updated, etc.

**Comment by gioragutt** [comment]
@timabbott yes please! I know docker for the basics, but it's unclear to me if I have to clone the repo or not, since it's required to edit the `docker-compose.yml` file...

Having clearer instructions would really help!

**Comment by timabbott** [comment]
@gioragutt I just finished the first pass of this; check out the new README.md.  I'd absolutely love it if you tried to follow the new documentation and offered any feedback on how it could be better!

**Comment by gioragutt** [comment]
Hey man, thank you so much for your work. I'm super busy for the rest of the day, but I'll definitely try it soon. I really want to get this to work(I want a slack-alternative and I need it to work on-premise), because this will have great value.

I'll let you know as soon as I get to this. Again, thank you for your work, it's really appreciated!
