### ISSUE TITLE
Blank Login Page on Startup

### ISSUE THREAD

**Issue by cmcneil** [Galexrt/docker-zulip#33]
![screenshot 2015-10-22 at 6 22 20 pm](https://cloud.githubusercontent.com/assets/865043/10682374/e250ef02-78e9-11e5-9faf-d578854eed23.png)

STEPS TO REPRODUCE:
----------------------------------
- Stop and remove all docker containers.
- Clone a fresh repository.
- Pull fresh images
  - `docker pull quay.io/galexrt/zulip`
  - `docker pull quay.io/galexrt/zulip-postgresql-tsearchextras`
- Make the following changes to `docker-compose.yml`
  - s/example\.com/mydomain\.org/g
  - Switch the ports from 80:80 -> 8080:80, and 443:443 -> 8443:443, to expose zulip on different host ports.
- Run `docker-compose up -d` (as root)
- Go to main page, https://convox.org:8443
- Login page doesn't work. (Nor does Register)

VERSION INFO:
----------------------
- Docker version 1.8.3, build f4bf5c7
- docker-compose version: 1.5.0rc1
- Host System(I can't imagine this is relevant): Linux leviathan 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

LOGS:
--------
- I checked `/var/log/zulip` in the `dockerzulip_zulip_1` container. Nothing in `errors.log`, and nothing suspicious in `server.log`. I can see my login requests, look normal:

`2015-10-22 21:43:42,262 INFO     208.54.4.232    GET     301   1ms /login (unauth via ?)`

`2015-10-22 21:43:42,478 INFO     208.54.4.232    GET     200  47ms (db: 1ms/1q) /login/ (unauth via ?`

Let me know if there's any particular log file that would be helpful.

**Comment by decker502** [comment]
Please try to register , show the result here

**Comment by Galexrt** [comment]
@decker502 Can you please check if the repo you have cloned is up to date?
The blank login page is occuring, because I changed the `ZULIP_AUTH_BACKENDS_EmailBackend` env var to `ZULIP_AUTH_BACKENDS`. Can you please reclone the repo and reconfigure your docker-compose.yml. It should fix the problem.

**Comment by Galexrt** [comment]
@decker502 This problem is related to my changes made to the `ZULIP_AUTH_BACKENDS` env var.

**Comment by decker502** [comment]
@Galexrt  sorry, I forget it. haha.

**Comment by cmcneil** [comment]
@Galexrt No, I don't think that's it, I tried switching it back and forth, and the login error occurs regardless. When I try to register I get a page like this:
![screenshot from 2015-10-23 16 25 50](https://cloud.githubusercontent.com/assets/865043/10707153/34f7a002-79a3-11e5-9ffe-30ec072178b9.png)

**Comment by cmcneil** [comment]
@Galexrt Question: do I actually need to be running an outgoing mail server for Zulip to function(postfix or something) on the host machine? Currently I've left these settings as default:
ZULIP_SETTINGS_EMAIL_HOST: "smtp.convox.org"
ZULIP_SETTINGS_EMAIL_HOST_USER: "noreply@convox.org"
And I'm not actually running a mail server at all. I assumed I would still be able to log in and get basic functionality without it, but maybe that's not true?

**Comment by Galexrt** [comment]
@cmcneil You don't need a working smtp server for this to work.
That's why I created the `ZULIP_USER_*` vars. They create an user.
For the user creation to work you have to remove the `/opt/docker/zulip/zulip/initiated` and restart the container or remove the current zulip volume folder and restart the container. Please check if your `docker-compose.yml` is up to date with the correct env vars. Because the empty Login page means that you need to set the `ZULIP_AUTH_BACKENDS` to `EmailAuthBackend` like in the docker-compose.yml.

For example for you @cmcneil, you would set them up like this:
```
ZULIP_USER_FULLNAME="Carson Mcneil"
ZULIP_USER_DOMAIN="example.com"
ZULIP_USER_EMAIL="carson.mcneil@example.com"
ZULIP_USER_PASS="123456789"
```

See for more details about the `ZULIP_USER_*` vars: https://github.com/Galexrt/docker-zulip/wiki/Env-Vars#zulip-user-creation

***

The only thing you should be aware of is that you can currently only create "one" user using the script.
Maybe I'll add it in one of the updates, that you can create more than one user with the script, without the need of a mail server.

**Comment by Galexrt** [comment]
@cmcneil We fixed the problem in IRC. It's working now.

**Comment by surajys** [comment]
I successfully registered 2 users. I got the registration mail also. 
If I click that link their profile page is opening. 
after logout  I am unable to login again using browser . (There is no username password field)
For me login link is not working . if I click that link nothing is happing,  only  page will redirect to  "https://zulip.example.com/login"   No error message  also. 
What is the issue ?

![loginissue](https://cloud.githubusercontent.com/assets/17525956/13378646/e9e165b8-de32-11e5-864b-78c77c033bc6.png)
