### ISSUE TITLE
Zulip not recognizing some set options

### ISSUE THREAD

**Issue by galexrt** [galexrt/docker-zulip#72]
```
+ su zulip -c '/home/zulip/deployments/current/manage.py checkconfig'
Error: You must set ALLOWED_HOSTS in /etc/zulip/settings.py.
```
This error occurs even when the `ALLOWED_HOSTS` default is in the `settings.py` and not having the `/etc/zulip/settings.py` linked..

@timabbott Do you have any idea why Zulip says `ALLOWED_HOSTS` is not set, when it is set?

**Comment by galexrt** [comment]
@tabbott Sorry for the wrong mention.

***

@timabbott Zulip is weirdly behaving with some options set in the `/etc/zulip/settings.py` file.

**Comment by timabbott** [comment]
The code throwing that error checks that the settings one has to configure for a Zulip server are to a value other than the default value.  In the case of `ALLOWED_HOSTS`, it's arguably wrong that the default value is "*", since even though "*" is a security problem, some folks will want to leave it at that value, and we currently prevent that.

**Comment by galexrt** [comment]
@timabbott Thanks for the information!
